# Generated by Django 4.1.5 on 2023-01-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_elements',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
