# Generated by Django 4.1.5 on 2023-01-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_rename_com_id_comments_id_rename_like_id_likes_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
