# Generated by Django 4.1.5 on 2023-01-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_remove_comments_user_alter_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Product.comments'),
        ),
    ]
