# Generated by Django 4.1.5 on 2023-01-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_product_comments_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
    ]
