# Generated by Django 4.1.5 on 2023-01-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_product_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='users',
            new_name='user',
        ),
    ]
