# Generated by Django 4.1.5 on 2023-01-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_alter_elements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_elements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.elements'),
        ),
    ]
