# Generated by Django 4.1.5 on 2023-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_cuisine_id_alter_elements_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_elements',
        ),
        migrations.AddField(
            model_name='product',
            name='product_elements',
            field=models.ManyToManyField(to='Product.elements'),
        ),
    ]
