# Generated by Django 4.1.5 on 2023-01-23 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0018_remove_product_product_elements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='dairy_prods',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='fruits',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='greens',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='meat',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='sauces',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='spices',
        ),
        migrations.RemoveField(
            model_name='elements',
            name='vegetables',
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ManyToManyField(to='Product.product'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elements',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='product',
        ),
        migrations.AddField(
            model_name='favourite',
            name='product',
            field=models.ManyToManyField(to='Product.product'),
        ),
    ]
