# Generated by Django 4.1.5 on 2023-01-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_remove_elements_dairy_prods_remove_elements_fruits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_elements',
        ),
    ]
