# Generated by Django 4.1.5 on 2023-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_product_product_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_elements',
        ),
        migrations.AddField(
            model_name='elements',
            name='product',
            field=models.ManyToManyField(to='Product.product'),
        ),
    ]
